name: CI (.NET)

on:
 pull_request:
  branches: [ "main" ]
 push:
  branches: [ "main" ]

permissions:
 contents: read

jobs:
 build_and_test:
  name: Buid & test
  runs-on: ubuntu-latest

  defaults:
   run:
    working-directory: apps/api

  steps:
   - name: Checkout
     uses: actions/checkout@v7

   - name: Setup .NET
     uses: actions/setup-dotnet@v5
     with:
      dotnet-version: "10.0.x"

   - name: Restore
     run: dotnet restore ./backbone.slnx

   - name: Build
     run: dotnet build ./backbone.slnx -c Release --no-restore

   - name: Test
     run: dotnet test ./backbone.slnx -c Release --no-build