name: Validate PR title

on:
 pull_request:
  types: [opened, edited, reopened, synchronize, ready_for_review]

jobs:
 pr-title:
  name: Check PR title matches convention
  runs-on: ubuntu-latest

  steps:
   - name: Validate title
     shell: bash
     run: |
      set -euo pipefail

      TITLE="${{ github.event.pull_request.title }}"
      ACTOR="${{ github.actor }}"
      BRANCH="${{ github.head_ref }}"

      echo "PR title: $TITLE"
      echo "Actor: $ACTOR"
      echo "Branch: $BRANCH"
      
      if [[ "$ACTOR" == "dependabot[bot]" || "$BRANCH" == dependabot/* ]]; then
       echo "✅ Dependabot PR detected. Skipping PR title validation."
       exit 0
      fi      

      # Format: type(scope): sumary

      REGEX='^(feat|fix|docs|refactor|test|chore|perf|ci)\([a-z0-9-]+\): [a-z][a-z0-9 ,._-].{2,}$'

      if [[ ! "$TITLE" =~ $REGEX ]]; then
       echo "::error title=Invalid PR title::'$TITLE' does not match 'type(scope): summary'"
       echo "Check documentation for convention"
       exit 1
      fi

      echo "✅ PR title matches convention."
